### PR TITLE
Fixed typo in README.md and langpack.ru.xml.

### PR DESCRIPTION
**Pull request by HenryDukart**
Fixed typo in README.md.

### CODE REVIEW

**Comment by Yukigaru** [comment]
Thanks! 
Just taking interest, will you try to send more pull requests? I will soon do massive code rework, will try to rewrite everything on Qt.

**Comment by HenryDukart** [comment]
It's a pity, but I totaly don't know wxWidgets. But I work with Qt. It will take some time to learn wx.

**Comment by Yamatao** [comment]
You don't need to know wxWidgets, currently I'm rewriting everything to Qt.

**Comment by Yamatao** [comment]
Thanks for the pull reqest!

**Pull request merged**
